[dbvrsgim]
h="localhost:27017"
d="vrsgim"
u="vrsgim"
p="vrsgim@234."
[dbchadmin]
h="localhost:27017"
d="cuahang"
u="cuahang"
p="cuahang1234@"
[config]
domainallow="http://localhost.com,http://duyhf.noip.me,http://localhost:8080"